site_name: Requisitos - Letterboxd
theme:
  name: material
  palette:
    scheme: slate
    primary: green
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - content.code.copy
markdown_extensions:
  - attr_list 
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

